# SPDX-License-Identifier: Apache-2.0
"""Mock incident analysis endpoint backed by the shared async incident writer."""

from __future__ import annotations

import asyncio
from pathlib import Path
import sys
import uuid

from fastapi import APIRouter
from fastapi import HTTPException
from pydantic import BaseModel

router = APIRouter(prefix="/api/v1")
_locks: dict[str, asyncio.Lock] = {}


class AnalyzeRequest(BaseModel):
    reasoning: bool = False


def _writer_module():
    root = Path(__file__).resolve().parents[9] / "services" / "agent" / "src"
    if str(root) not in sys.path:
        sys.path.insert(0, str(root))
    from vss_agents.utils import incident_db

    return incident_db


@router.post("/incidents/{incident_id}/analyze")
async def analyze_incident(incident_id: str, body: AnalyzeRequest) -> dict[str, object]:
    """Persist one deterministic, explicitly mock report for an uploaded video."""
    if not incident_id or len(incident_id) > 20:
        raise HTTPException(400, "invalid video id")
    writer = _writer_module()
    db = await writer.get_db()
    if db is None:
        raise HTTPException(503, "incident database is not configured or unavailable")
    lock = _locks.setdefault(incident_id, asyncio.Lock())
    async with lock:
        video = await db.get_video(incident_id)
        if video is None:
            raise HTTPException(404, "video not found")
        model_run_id = "mock-run-" + uuid.uuid4().hex[:11]
        report_id = "mock-rpt-" + uuid.uuid4().hex[:10]
        async with db.transaction() as tx:
            await tx.insert_model_run(
                model_run_id,
                model_name="base-profile-mock",
                model_version="mock-v1",
                prompt_version="mock-incident-v1",
                notes="MOCK output generated by base_profile_mock; no VSS inference was run.",
            )
            await tx.insert_incident(
                incident_id,
                model_run_id,
                fields={
                    "type": "fighting",
                    "start_timestamp": "00:00:00",
                    "end_timestamp": "00:00:10",
                    "duration": 10,
                    "description": "MOCK incident report: two people are involved in a physical altercation.",
                    "severity_level": 3,
                    "confidence_score": 0.91,
                },
            )
            await tx.add_incident_entity(
                incident_id,
                model_run_id,
                entity_id="person-1",
                type="human",
                description="MOCK detected person involved in the incident.",
            )
            await tx.insert_generated_report(
                report_id,
                incident_id=incident_id,
                model_run_id=model_run_id,
                filepath=f"mock://reports/{report_id}.md",
            )
    return {
        "status": "completed",
        "video_id": incident_id,
        "model_run_id": model_run_id,
        "report_id": report_id,
        "mock": True,
        "reasoning": body.reasoning,
    }
