// SPDX-License-Identifier: Apache-2.0

import { NextResponse } from 'next/server';
import { z } from 'zod';
import { getServiceConfiguration, isSupabaseConfigured } from '@/lib/env';
import { errorResponse } from '@/lib/http';
import { PostgrestClient } from '@/lib/postgrest/client';

const schema = z.object({ modelRunId: z.string().min(1), type: z.string().trim().min(1), description: z.string().trim().min(1), startTimestamp: z.string().nullable(), endTimestamp: z.string().nullable(), duration: z.number().int().nonnegative().nullable(), severityLevel: z.number().int().min(1).max(5), labelledBy: z.string().trim().min(1) });
function dbClient() { const config = getServiceConfiguration(); if (!isSupabaseConfigured(config)) throw new Error('Supabase PostgREST is not configured'); return new PostgrestClient(config.supabaseUrl!, config.supabaseServiceRoleKey!); }
export async function GET(_: Request, context: { params: Promise<{ videoId: string }> }) { try { const { videoId } = await context.params; const db = dbClient(); const [incident, entities, instruments, assets] = await Promise.all([db.selectOne('gt_incidents', { incident_id: videoId }), db.selectMany('gt_entities', { filters: { incident_id: videoId } }), db.selectMany('gt_instruments', { filters: { incident_id: videoId } }), db.selectMany('gt_assets', { filters: { incident_id: videoId } })]); return NextResponse.json({ groundTruth: incident, entities, instruments, assets }); } catch (error) { return errorResponse(error, 'Could not load ground truth'); } }
export async function PUT(request: Request, context: { params: Promise<{ videoId: string }> }) { try { const { videoId } = await context.params; const input = schema.parse(await request.json()); const db = dbClient(); const now = new Date().toISOString(); await db.upsert('gt_incidents', { incident_id: videoId, type: input.type, description: input.description, start_timestamp: input.startTimestamp, end_timestamp: input.endTimestamp, duration: input.duration, severity_level: input.severityLevel, labelled_by: input.labelledBy, labelled_datetime: now }, 'incident_id'); const ai = await db.selectOne('incidents', { incident_id: videoId, model_run_id: input.modelRunId }); await db.upsert('severity_eval_log', { incident_id: videoId, model_run_id: input.modelRunId, ai_severity: typeof ai?.severity_level === 'number' ? ai.severity_level : null, human_severity: input.severityLevel, rater: input.labelledBy, rated_at: now }); return NextResponse.json({ saved: true }); } catch (error) { return errorResponse(error, 'Could not save ground truth'); } }
