// SPDX-License-Identifier: Apache-2.0

'use client';
import Link from 'next/link';
import { FormEvent, useEffect, useState } from 'react';
import type { AnalysisReport } from '@/lib/analysis/schema';
import type { ReportLibraryItem } from '@/lib/reports/storage';

export function AdvancedReportTools({ report }: { report: AnalysisReport }) {
  return (
    <>
      <section className="print-hidden mt-6 grid gap-6 xl:grid-cols-3">
        <ReportEditor report={report} />
        <FollowUpChat report={report} />
        <ComparisonAndEvaluation report={report} />
      </section>
      <RunComparisonLauncher report={report} />
    </>
  );
}

function RunComparisonLauncher({ report }: { report: AnalysisReport }) {
  const [other, setOther] = useState<ReportLibraryItem | null>(null);
  useEffect(() => { void fetch('/api/reports').then((r) => r.json()).then((p: { reports?: ReportLibraryItem[] }) => { setOther((p.reports || []).find((item) => item.videoId === report.videoId && item.modelRunId !== report.modelRunId) || null); }); }, [report]);
  if (!other) return null;
  return <div className="print-hidden mt-6 rounded-2xl border border-signal/25 bg-signal/5 p-5 text-sm"><strong>Another model run is available for this video.</strong><Link className="ml-3 font-bold text-moss" href={`/reports/${encodeURIComponent(report.videoId)}/compare?left=${encodeURIComponent(report.modelRunId)}&right=${encodeURIComponent(other.modelRunId)}`}>Compare runs side by side →</Link></div>;
}

function ReportEditor({ report }: { report: AnalysisReport }) {
  const [form, setForm] = useState({ incident_type: report.incident_type, description: report.description, incident_start: report.incident_start || '', incident_end: report.incident_end || '', severity: report.severity, confidence: report.confidence }); const [message, setMessage] = useState('');
  async function submit(event: FormEvent) { event.preventDefault(); const editor = window.prompt('Your name is required for the edit history.'); if (!editor?.trim()) return; if (report.reviewStatus === 'verified' && !window.confirm('This report is verified. Save these corrections anyway?')) return; setMessage('Saving…'); const response = await fetch(`/api/reports/${encodeURIComponent(report.videoId)}/edit`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ ...form, incident_start: form.incident_start || null, incident_end: form.incident_end || null, modelRunId: report.modelRunId, editor }) }); const payload = await response.json() as { error?: string }; setMessage(response.ok ? 'Saved. Reload to see the corrected report.' : payload.error || 'Save failed'); }
  return <form className="rounded-3xl border border-ink/10 bg-white p-6" onSubmit={submit}><p className="font-mono text-xs uppercase tracking-[.15em] text-moss">Human corrections</p><h2 className="mt-2 text-xl font-semibold">Edit structured report</h2><label className="mt-4 block text-xs font-bold">Incident type<input className="control mt-1" onChange={(e) => setForm({ ...form, incident_type: e.target.value })} value={form.incident_type} /></label><label className="mt-3 block text-xs font-bold">Summary<textarea className="control mt-1 min-h-[100px]" onChange={(e) => setForm({ ...form, description: e.target.value })} value={form.description} /></label><div className="mt-3 grid grid-cols-2 gap-2"><label className="text-xs font-bold">Start<input className="control mt-1" onChange={(e) => setForm({ ...form, incident_start: e.target.value })} value={form.incident_start} /></label><label className="text-xs font-bold">End<input className="control mt-1" onChange={(e) => setForm({ ...form, incident_end: e.target.value })} value={form.incident_end} /></label><label className="text-xs font-bold">Severity<input className="control mt-1" max={5} min={1} onChange={(e) => setForm({ ...form, severity: Number(e.target.value) })} type="number" value={form.severity} /></label><label className="text-xs font-bold">Confidence<input className="control mt-1" max={1} min={0} onChange={(e) => setForm({ ...form, confidence: Number(e.target.value) })} step="0.01" type="number" value={form.confidence} /></label></div><button className="mt-4 rounded-full bg-ink px-4 py-2 text-xs font-semibold text-white" type="submit">Save corrections</button>{message && <p className="mt-3 text-xs text-ink/55">{message}</p>}</form>;
}

function FollowUpChat({ report }: { report: AnalysisReport }) {
  const [messages, setMessages] = useState<Array<{ role: 'user' | 'assistant'; content: string }>>([]); const [question, setQuestion] = useState(''); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  async function ask(event: FormEvent) { event.preventDefault(); if (!question.trim() || busy) return; const next = [...messages, { role: 'user' as const, content: question.trim() }]; setMessages(next); setQuestion(''); setBusy(true); setError(''); try { const response = await fetch('/api/chat', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ messages: next, reportContext: JSON.stringify({ title: report.title, description: report.description, timeline: report.timeline, persons: report.persons, instruments: report.instruments, assets: report.assets, uncertainties: report.uncertainties }) }) }); const payload = await response.json() as { content?: string; error?: string }; if (!response.ok || !payload.content) throw new Error(payload.error || 'No answer returned'); setMessages([...next, { role: 'assistant', content: payload.content }]); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Chat failed'); } finally { setBusy(false); } }
  return <section className="flex min-h-[420px] flex-col rounded-3xl border border-ink/10 bg-white p-6"><p className="font-mono text-xs uppercase tracking-[.15em] text-moss">Report-grounded</p><h2 className="mt-2 text-xl font-semibold">Ask a follow-up</h2><div className="mt-4 flex-1 space-y-3 overflow-auto">{messages.length === 0 && <p className="text-sm leading-6 text-ink/45">Ask about timestamps, people, objects, evidence, or uncertainty. Answers use this stored report as context.</p>}{messages.map((m, i) => <div className={`rounded-2xl p-3 text-sm leading-6 ${m.role === 'user' ? 'ml-8 bg-ink text-white' : 'mr-8 bg-canvas text-ink/70'}`} key={i}>{m.content}</div>)}</div>{error && <p className="mt-2 text-xs text-clay">{error}</p>}<form className="mt-4 flex gap-2" onSubmit={ask}><input aria-label="Follow-up question" className="control" onChange={(e) => setQuestion(e.target.value)} placeholder="What happened before…?" value={question} /><button className="rounded-full bg-moss px-4 text-xs font-semibold text-white disabled:opacity-50" disabled={busy} type="submit">{busy ? 'Thinking…' : 'Ask'}</button></form></section>;
}

function ComparisonAndEvaluation({ report }: { report: AnalysisReport }) {
  const [runs, setRuns] = useState<ReportLibraryItem[]>([]); const [gt, setGt] = useState({ type: report.incident_type, description: report.description, startTimestamp: report.incident_start || '', endTimestamp: report.incident_end || '', severityLevel: report.severity }); const [message, setMessage] = useState('');
  useEffect(() => { void fetch('/api/reports').then((r) => r.json()).then((p: { reports?: ReportLibraryItem[] }) => setRuns((p.reports || []).filter((item) => item.videoId === report.videoId))); void fetch(`/api/reports/${encodeURIComponent(report.videoId)}/ground-truth`).then((r) => r.json()).then((p: { groundTruth?: Record<string, unknown> | null }) => { const g = p.groundTruth; if (g) setGt({ type: String(g.type || ''), description: String(g.description || ''), startTimestamp: String(g.start_timestamp || ''), endTimestamp: String(g.end_timestamp || ''), severityLevel: Number(g.severity_level || 1) }); }); }, [report]);
  async function saveGroundTruth() { const labelledBy = window.prompt('Evaluator name'); if (!labelledBy?.trim()) return; const response = await fetch(`/api/reports/${encodeURIComponent(report.videoId)}/ground-truth`, { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ ...gt, startTimestamp: gt.startTimestamp || null, endTimestamp: gt.endTimestamp || null, duration: report.duration_seconds, modelRunId: report.modelRunId, labelledBy }) }); const payload = await response.json() as { error?: string }; setMessage(response.ok ? 'Ground truth and severity evaluation saved.' : payload.error || 'Save failed'); }
  return <section className="rounded-3xl border border-ink/10 bg-white p-6"><p className="font-mono text-xs uppercase tracking-[.15em] text-moss">Evaluation</p><h2 className="mt-2 text-xl font-semibold">Runs and ground truth</h2><div className="mt-4"><p className="text-xs font-bold uppercase tracking-wider text-ink/40">Model runs for this video</p><div className="mt-2 space-y-2">{runs.map((run) => <Link className={`block rounded-xl border p-3 text-xs ${run.modelRunId === report.modelRunId ? 'border-signal bg-signal/5' : 'border-ink/10'}`} href={`/reports/${encodeURIComponent(run.videoId)}?run=${encodeURIComponent(run.modelRunId)}`} key={run.modelRunId}><strong>{run.model}</strong><span className="mt-1 block text-ink/45">Severity {run.severity} · {Math.round(run.confidence * 100)}% · {new Date(run.generatedAt).toLocaleString()}</span></Link>)}</div></div><div className="mt-5 border-t border-ink/10 pt-5"><p className="text-xs font-bold uppercase tracking-wider text-ink/40">Human ground truth</p><input className="control mt-2" onChange={(e) => setGt({ ...gt, type: e.target.value })} placeholder="Incident type" value={gt.type} /><textarea className="control mt-2 min-h-[80px]" onChange={(e) => setGt({ ...gt, description: e.target.value })} placeholder="Human description" value={gt.description} /><div className="mt-2 grid grid-cols-3 gap-2"><input className="control" onChange={(e) => setGt({ ...gt, startTimestamp: e.target.value })} placeholder="Start" value={gt.startTimestamp} /><input className="control" onChange={(e) => setGt({ ...gt, endTimestamp: e.target.value })} placeholder="End" value={gt.endTimestamp} /><input aria-label="Human severity" className="control" max={5} min={1} onChange={(e) => setGt({ ...gt, severityLevel: Number(e.target.value) })} type="number" value={gt.severityLevel} /></div><button className="mt-3 rounded-full bg-ink px-4 py-2 text-xs font-semibold text-white" onClick={() => void saveGroundTruth()} type="button">Save evaluation</button>{message && <p className="mt-2 text-xs text-ink/55">{message}</p>}</div></section>;
}
