// SPDX-License-Identifier: Apache-2.0
'use client';
import Link from 'next/link';
import { useEffect, useMemo, useState } from 'react';
import type { DashboardAnalytics, RankedValue, SeverityCounts, TypeDetail } from '@/lib/dashboard/types';

type Filters = { type: string; severity: string; day: string; hour: string };
const NONE: Filters = { type: '', severity: '', day: '', hour: '' };
const DAYS = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'];
const EMPTY: DashboardAnalytics = { total: 0, previous: null, averageConfidence: 0, severity: { low: 0, medium: 0, high: 0 }, reviews: { unreviewed: 0, under_review: 0, verified: 0 }, types: [], trend: [], heatmap: [], confidence: [], topEntities: [], topAssets: [] };

export function Dashboard() {
  const [data, setData] = useState(EMPTY); const [days, setDays] = useState('30'); const [compare, setCompare] = useState(true);
  const [filters, setFilters] = useState<Filters>(NONE); const [expanded, setExpanded] = useState(''); const [error, setError] = useState('');
  useEffect(() => { const controller = new AbortController(); const params = new URLSearchParams({ days }); Object.entries(filters).forEach(([k, v]) => { if (v) params.set(k, v); }); setError(''); fetch(`/api/dashboard?${params}`, { cache: 'no-store', signal: controller.signal }).then(async (r) => { const p = await r.json() as { analytics?: DashboardAnalytics; error?: string }; if (!r.ok || !p.analytics) throw new Error(p.error || 'Could not load dashboard'); setData(p.analytics); }).catch((e: Error) => { if (e.name !== 'AbortError') setError(e.message); }); return () => controller.abort(); }, [days, filters]);
  const previous = compare ? data.previous : null; const active = Object.values(filters).some(Boolean); const maxType = Math.max(1, ...data.types.map((x) => x.count));
  const toggle = (key: keyof Filters, value: string) => setFilters((f) => ({ ...f, [key]: f[key] === value ? '' : value }));
  return <div className="mx-auto max-w-[1500px] px-6 pb-20 pt-8 lg:px-12">
    <div className="flex flex-wrap items-end justify-between gap-4"><div><p className="font-mono text-xs uppercase tracking-[.2em] text-moss">Verified intelligence</p><h1 className="mt-2 text-4xl font-semibold sm:text-5xl">Operations dashboard</h1><p className="mt-3 text-sm text-ink/50">Explore patterns, then carry the exact context into the report library.</p></div><div className="flex items-center gap-3"><label className="text-sm"><input checked={compare} disabled={days === 'all'} onChange={(e) => setCompare(e.target.checked)} type="checkbox" /> <span className="ml-1">vs. previous period</span></label><select className="control w-auto" onChange={(e) => setDays(e.target.value)} value={days}><option value="7">Last 7 days</option><option value="30">Last 30 days</option><option value="all">All time</option></select></div></div>
    {active && <div className="mt-5 flex items-center rounded-2xl border border-moss/20 bg-white p-4 text-sm"><strong className="text-moss">Dashboard filters active</strong><span className="ml-3 text-ink/50">{[filters.type, filters.severity, filters.day && DAYS[+filters.day], filters.hour && `${filters.hour}:00`].filter(Boolean).join(' · ')}</span><button className="ml-auto font-semibold text-moss" onClick={() => setFilters(NONE)} type="button">Reset</button></div>}
    {error && <p className="mt-6 rounded-2xl border border-clay/30 bg-white p-4 text-clay">{error}</p>}
    <section className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Metric change={delta(data.total, previous?.total)} href={href(filters)} label="Reports" value={data.total} /><Metric change={delta(data.reviews.verified, previous?.verified)} href={href({ ...filters, status: 'verified' })} label="Verified" value={data.reviews.verified} /><Metric change={delta(data.reviews.unreviewed, previous?.unreviewed)} href={href({ ...filters, status: 'unreviewed' })} label="Awaiting review" value={data.reviews.unreviewed} /><Metric change={delta(data.severity.high, previous?.high)} href={href({ ...filters, severity: 'high' })} label="High severity" value={data.severity.high} /></section>
    <div className="mt-6 grid gap-6 xl:grid-cols-[1.4fr_.8fr]"><Panel title="Reports trend" subtitle="Daily counts in the selected period"><Trend points={data.trend} /></Panel><Panel title="Severity breakdown" subtitle="Click a segment to cross-filter"><Severity counts={data.severity} selected={filters.severity} onSelect={(v) => toggle('severity', v)} /></Panel></div>
    <div className="mt-6 grid gap-6 xl:grid-cols-[1.2fr_.8fr]"><Panel title="Incidents by type" subtitle="Expand a row for evidence and severity"><div className="space-y-2">{data.types.map((item) => <TypeRow expanded={expanded === item.type} item={item} key={item.type} max={maxType} onToggle={() => setExpanded(expanded === item.type ? '' : item.type)} />)}{!data.types.length && <Empty />}</div></Panel><Panel title="Review funnel" subtitle="Awaiting review → In review → Verified"><Funnel data={data} /></Panel></div>
    <div className="mt-6 grid gap-6 xl:grid-cols-2"><Panel title="Report activity by day and time" subtitle="Generation time; click a cell to cross-filter"><Heatmap data={data.heatmap} selected={`${filters.day}-${filters.hour}`} onSelect={(d, h) => setFilters((f) => f.day === String(d) && f.hour === String(h) ? { ...f, day: '', hour: '' } : { ...f, day: String(d), hour: String(h) })} /></Panel><Panel title="Confidence distribution" subtitle={`Average confidence ${Math.round(data.averageConfidence * 100)}%`}><Histogram data={data.confidence} /></Panel></div>
    <div className="mt-6 grid gap-6 xl:grid-cols-2"><Panel title="Top entities and people" subtitle="Recurring actors across incident types"><Leaders filters={filters} items={data.topEntities} kind="entity" /></Panel><Panel title="Top assets affected" subtitle="Most frequently involved property"><Leaders filters={filters} items={data.topAssets} kind="asset" /></Panel></div>
  </div>;
}

type LinkFilters = Filters & { status?: string; entity?: string; instrument?: string; asset?: string };
function href(f: LinkFilters) { const p = new URLSearchParams(); if (f.type) p.set('type', f.type); if (f.severity === 'high' || /^[1-5]$/.test(f.severity)) p.set('severity', f.severity); if (f.status) p.set('status', f.status); if (f.entity) p.set('entity', f.entity); if (f.instrument) p.set('instrument', f.instrument); if (f.asset) p.set('asset', f.asset); if (f.hour) { p.set('fromTime', `${f.hour.padStart(2, '0')}:00`); p.set('toTime', `${f.hour.padStart(2, '0')}:59`); } const query = p.toString(); return `/reports${query ? `?${query}` : ''}`; }
function delta(now: number, before?: number) { if (before === undefined) return null; return before ? Math.round((now - before) / before * 100) : now ? 100 : 0; }
function Metric({ label, value, href: url, change }: { label: string; value: number; href: string; change: number | null }) { return <Link className="rounded-2xl border border-ink/10 bg-white p-5 hover:shadow-panel" href={url}><p className="text-sm text-ink/50">{label}</p><p className="mt-2 text-4xl font-semibold">{value}</p>{change !== null && <p className="mt-2 text-xs text-ink/45">{change > 0 ? '+' : ''}{change}% vs. previous</p>}</Link>; }
function Panel({ title, subtitle, children }: { title: string; subtitle: string; children: React.ReactNode }) { return <section className="rounded-3xl border border-ink/10 bg-white p-6"><h2 className="text-lg font-semibold">{title}</h2><p className="mt-1 text-xs text-ink/45">{subtitle}</p><div className="mt-5">{children}</div></section>; }

function TypeRow({ item, expanded, max, onToggle }: { item: TypeDetail; expanded: boolean; max: number; onToggle: () => void }) { return <article className="rounded-2xl border border-ink/8"><button aria-expanded={expanded} className="w-full p-4 text-left" onClick={onToggle} type="button"><div className="flex justify-between text-sm"><strong className="capitalize">{item.type}</strong><span>{item.count} {expanded ? '−' : '+'}</span></div><div className="mt-2 h-2 rounded-full bg-ink/8"><div className="h-2 rounded-full bg-signal" style={{ width: `${item.count / max * 100}%` }} /></div></button>{expanded && <div className="border-t border-ink/8 p-4"><div className="grid gap-4 md:grid-cols-3"><Evidence title="People & entities" items={item.entities} kind="entity" type={item.type} /><Evidence title="Instruments" items={item.instruments} kind="instrument" type={item.type} /><Evidence title="Assets affected" items={item.assets} kind="asset" type={item.type} /></div><div className="mt-5"><p className="text-[10px] font-bold uppercase text-ink/40">Severity split</p><Severity compact counts={item.severity} selected="" onSelect={() => undefined} /></div><Link className="mt-5 inline-block text-sm font-semibold text-moss" href={href({ ...NONE, type: item.type })}>View all {item.type} reports →</Link></div>}</article>; }
function Evidence({ title, items, kind, type }: { title: string; items: RankedValue[]; kind: 'entity' | 'instrument' | 'asset'; type: string }) { return <div><p className="text-[10px] font-bold uppercase text-ink/40">{title}</p><div className="mt-2 space-y-1">{items.map((x) => <Link className="flex gap-2 text-sm text-moss" href={href({ ...NONE, type, [kind]: x.label })} key={x.label}><span className="min-w-0 flex-1 truncate">{x.label}</span><span>{x.count}</span></Link>)}{!items.length && <span className="text-xs text-ink/35">None identified</span>}</div></div>; }
function Severity({ counts, selected, onSelect, compact = false }: { counts: SeverityCounts; selected: string; onSelect: (v: string) => void; compact?: boolean }) { const total = counts.low + counts.medium + counts.high; const rows = [['low', 'Low', 'bg-signal'], ['medium', 'Medium', 'bg-amber-400'], ['high', 'High', 'bg-clay']] as const; return <div><div className={`flex overflow-hidden rounded-full bg-ink/8 ${compact ? 'mt-2 h-2' : 'h-5'}`}>{rows.map(([k, label, color]) => <button aria-label={`${label} severity`} className={`${color} ${selected && selected !== k ? 'opacity-25' : ''}`} disabled={compact} key={k} onClick={() => onSelect(k)} style={{ width: `${total ? counts[k] / total * 100 : 0}%` }} type="button" />)}</div><div className="mt-3 grid grid-cols-3 text-xs">{rows.map(([k, label]) => <button disabled={compact} key={k} onClick={() => onSelect(k)} type="button"><strong className="block text-base">{counts[k]}</strong>{label}</button>)}</div></div>; }
function Trend({ points }: { points: DashboardAnalytics['trend'] }) { const max = Math.max(1, ...points.map((x) => x.count)); const line = points.map((x, i) => `${points.length === 1 ? 50 : i / (points.length - 1) * 100},${38 - x.count / max * 32}`).join(' '); return points.length ? <div><svg aria-label="Daily report trend" className="h-48 w-full" preserveAspectRatio="none" role="img" viewBox="0 0 100 40"><polyline fill="none" points={line} stroke="#315b3a" strokeWidth="1.5" vectorEffect="non-scaling-stroke" /></svg><div className="flex justify-between text-[10px] text-ink/40"><span>{points[0].date}</span><span>{points.at(-1)?.date}</span></div></div> : <Empty />; }
function Heatmap({ data, selected, onSelect }: { data: DashboardAnalytics['heatmap']; selected: string; onSelect: (d: number, h: number) => void }) { const map = useMemo(() => new Map(data.map((x) => [`${x.day}-${x.hour}`, x.count])), [data]); const max = Math.max(1, ...data.map((x) => x.count)); return <div className="overflow-x-auto"><div className="min-w-[650px]">{DAYS.map((name, d) => <div className="mt-1 grid grid-cols-[32px_repeat(24,1fr)] gap-1" key={name}><span className="text-[10px]">{name}</span>{Array.from({ length: 24 }, (_, h) => { const count = map.get(`${d}-${h}`) || 0; return <button aria-label={`${name} ${h}:00: ${count}`} className={`aspect-square rounded-sm ${selected === `${d}-${h}` ? 'ring-2 ring-ink' : ''}`} key={h} onClick={() => onSelect(d, h)} style={{ background: `rgba(49,91,58,${count ? .15 + count / max * .85 : .04})` }} title={`${name} ${h}:00 · ${count}`} type="button" />; })}</div>)}</div></div>; }
function Funnel({ data }: { data: DashboardAnalytics }) { const rows = [['Awaiting review', data.reviews.unreviewed, 'bg-clay/50'], ['In review', data.reviews.under_review, 'bg-amber-300'], ['Verified', data.reviews.verified, 'bg-signal']] as const; const max = Math.max(1, ...rows.map((x) => x[1])); return <div className="space-y-4">{rows.map(([label, count, color]) => <div key={label}><div className="flex justify-between text-sm"><span>{label}</span><strong>{count}</strong></div><div className="mt-2 h-7 rounded bg-ink/5"><div className={`h-7 rounded ${color}`} style={{ width: `${count / max * 100}%` }} /></div></div>)}</div>; }
function Histogram({ data }: { data: DashboardAnalytics['confidence'] }) { const map = new Map(data.map((x) => [x.bucket, x.count])); const max = Math.max(1, ...data.map((x) => x.count)); return <div className="flex h-48 items-end gap-2">{Array.from({ length: 10 }, (_, b) => <div className="flex h-full flex-1 flex-col justify-end text-center" key={b}><span className="text-[9px]">{map.get(b) || ''}</span><div className="min-h-1 bg-moss/75" style={{ height: `${(map.get(b) || 0) / max * 100}%` }} /><span className="mt-1 text-[9px]">{b * 10}</span></div>)}</div>; }
function Leaders({ items, kind, filters }: { items: RankedValue[]; kind: 'entity' | 'asset'; filters: Filters }) { const max = Math.max(1, ...items.map((x) => x.count)); return <div className="space-y-4">{items.map((x, i) => <Link className="block" href={href({ ...filters, [kind]: x.label })} key={x.label}><div className="flex gap-3 text-sm"><span className="text-ink/30">{i + 1}</span><span className="min-w-0 flex-1 truncate">{x.label}</span><strong>{x.count}</strong></div><div className="ml-6 mt-2 h-1.5 bg-ink/8"><div className="h-1.5 bg-signal" style={{ width: `${x.count / max * 100}%` }} /></div></Link>)}{!items.length && <Empty />}</div>; }
function Empty() { return <p className="text-sm text-ink/40">No reports in this selection.</p>; }
