// SPDX-License-Identifier: Apache-2.0

'use client';

import { useRef, useState, type ReactNode } from 'react';

import { OfficialControls } from '@/components/official-controls';
import { StructuredEditor } from '@/components/structured-editor';
import { timestampWithinVideo } from '@/lib/contract/video-bounds';
import type { ReviewStatus } from '@/lib/reports/storage';
import { formatClock } from '@/lib/reports/normalize';
import { reportHeading, type ReportView } from '@/lib/reports/report-view';
import { formatTimestamp } from '@/lib/time';

function severityStyle(level: number | null): string {
  if (level !== null && level >= 4) return 'bg-[#ffe8df] text-[#9b3518]';
  if (level === 3) return 'bg-[#fff1c7] text-[#765300]';
  return 'bg-signal/15 text-moss';
}

function capitalize(value: string | null): string {
  return value ? value[0].toUpperCase() + value.slice(1) : 'Unclassified';
}

function statusLabel(status: ReviewStatus): string {
  return status === 'under review' ? 'Under review' : status[0].toUpperCase() + status.slice(1);
}

export function IncidentReport({ report, onNewAnalysis, onEdited }: { report: ReportView; onNewAnalysis: () => void; onEdited?: () => void }) {
  const { structured, modelOutput, run, differences } = report;
  const { incident } = structured;
  const videoRef = useRef<HTMLVideoElement>(null);
  const [copied, setCopied] = useState(false);
  const [reviewStatus, setReviewStatus] = useState<ReviewStatus>(report.review.status);
  const [reviewBusy, setReviewBusy] = useState(false);
  const [editing, setEditing] = useState(false);
  // The player's own length, a second guard (besides the recorded length) before jumping to a timeline time.
  const [playerDuration, setPlayerDuration] = useState<number | null>(null);
  const windowEdited = differences.fields.includes('incident window');
  const original = modelOutput?.original;
  const holderLabel = new Map(structured.entities.map((entity) => [entity.entityId, `${entity.entityId} (${entity.type})`]));

  function seek(seconds: number) {
    if (!videoRef.current) return;
    videoRef.current.currentTime = seconds;
    void videoRef.current.play();
  }

  async function copyLink() {
    await navigator.clipboard.writeText(window.location.href);
    setCopied(true);
    window.setTimeout(() => setCopied(false), 1800);
  }

  async function changeReviewStatus(status: ReviewStatus) {
    const reviewer = window.prompt(`Your name is required to mark this report ${status}.`);
    if (!reviewer?.trim()) return;
    if (status === 'verified' && !window.confirm('Verify this report as reviewed and accurate?')) return;
    setReviewBusy(true);
    try {
      const response = await fetch(`/api/reports/${encodeURIComponent(report.videoId)}/review`, {
        method: 'PATCH',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ modelRunId: report.modelRunId, status, reviewedBy: reviewer }),
      });
      const payload = (await response.json()) as { error?: string };
      if (!response.ok) throw new Error(payload.error || 'Review update failed');
      setReviewStatus(status);
    } catch (error) {
      window.alert(error instanceof Error ? error.message : 'Review update failed');
    } finally {
      setReviewBusy(false);
    }
  }

  return (
    <article className="report-sheet overflow-hidden rounded-[2rem] border border-ink/10 bg-white shadow-panel">
      <div className="print-hidden flex flex-wrap items-center justify-between gap-3 border-b border-ink/10 bg-white px-6 py-3 text-xs">
        <span className="text-ink/45">Report {run.reportId}</span>
        <div className="flex gap-4">
          <button className="font-semibold text-moss" onClick={copyLink} type="button">{copied ? 'Link copied' : 'Copy link'}</button>
          <button className="font-semibold text-moss" onClick={() => window.print()} type="button">Print report</button>
          <button className="font-semibold text-moss" onClick={onNewAnalysis} type="button">New analysis</button>
        </div>
      </div>

      <header className="border-b border-ink/10 bg-[#eef2e9] p-6 sm:p-8">
        <div className="flex flex-col gap-5 sm:flex-row sm:items-start sm:justify-between">
          <div>
            <p className="font-mono text-[11px] uppercase tracking-[0.2em] text-moss">
              Incident report{run.notesKind === 'legacy' ? ' · earlier prompt version' : ''}{report.official.isOfficial ? ' · official' : ''}
            </p>
            <h2 className="mt-3 text-3xl font-semibold tracking-[-0.035em] sm:text-4xl">{reportHeading(report)}</h2>
            {modelOutput?.title && <p className="mt-1 text-xs text-ink/40">Title generated by the model{differences.fields.length ? ' (before reviewer edits)' : ''}</p>}
            <p className="mt-3 text-sm text-ink/55">
              {capitalize(incident.type)}{modelOutput?.location ? ` · ${modelOutput.location}` : ''} · {run.filename}
            </p>
            {run.status === 'valid_after_structural_repair' && (
              <p className="mt-3 mr-2 inline-block rounded-full bg-[#fff1c7] px-3 py-1 text-xs font-semibold text-[#765300]" data-testid="contract-repair-applied">
                Contract repair applied (IDs only)
              </p>
            )}
            {differences.fields.length > 0 && (
              <p className="mt-3 inline-block rounded-full bg-white px-3 py-1 text-xs font-semibold text-clay" data-testid="reviewer-edited">
                Reviewer-edited after generation: {differences.fields.join(', ')}
              </p>
            )}
            {differences.type && (
              <p className="mt-2 text-xs font-semibold text-clay" data-testid="type-edited">Model classified this as {differences.type.model}; reviewer set {differences.type.current}.</p>
            )}
          </div>
          <div className="flex shrink-0 gap-2">
            <span className={`rounded-full px-4 py-2 text-sm font-bold ${severityStyle(incident.severityLevel)}`}>
              Severity {incident.severityLevel ?? '—'}/5
            </span>
            {incident.confidenceScore !== null && (
              <span className="rounded-full bg-white px-4 py-2 text-sm font-semibold text-ink/65">{Math.round(incident.confidenceScore * 100)}% confidence</span>
            )}
          </div>
        </div>
      </header>

      <section className="print-hidden flex flex-col gap-3 border-b border-ink/10 bg-white px-6 py-4 sm:flex-row sm:items-center sm:justify-between sm:px-8">
        <div>
          <p className="text-xs font-bold uppercase tracking-[0.12em] text-ink/40">Human review</p>
          <p className="mt-1 text-sm text-ink/60">Current status: <strong className="text-ink">{statusLabel(reviewStatus)}</strong></p>
          <p className="mt-1 text-xs text-ink/55" data-testid="official-status">
            {report.official.isOfficial
              ? `Official report for this video · selected by ${report.official.selectedBy ?? 'a reviewer'} on ${formatTimestamp(report.official.selectedAt)}`
              : report.official.officialRunId ? 'Another analysis is the official report for this video.' : 'No official report has been selected for this video.'}
          </p>
          {report.review.editedBy && report.review.editedAt && (
            <p className="mt-1 text-xs text-ink/45" data-testid="last-edited">Structured fields last edited by {report.review.editedBy} on {formatTimestamp(report.review.editedAt)}</p>
          )}
        </div>
        <div className="flex flex-wrap items-center gap-2">
          <OfficialControls hasOfficial={Boolean(report.official.officialRunId)} isOfficial={report.official.isOfficial} modelRunId={report.modelRunId} onChanged={() => onEdited?.()} videoId={report.videoId} />
          <button className="action" disabled={editing} onClick={() => setEditing(true)} type="button">{editing ? 'Editing report' : 'Edit report'}</button>
          {reviewStatus !== 'verified' && <button className="rounded-full bg-moss px-4 py-2 text-xs font-semibold text-white disabled:opacity-50" disabled={reviewBusy} onClick={() => void changeReviewStatus('verified')} type="button">Verify report</button>}
          {reviewStatus !== 'unreviewed' && <button className="action" disabled={reviewBusy} onClick={() => void changeReviewStatus('unreviewed')} type="button">Reset review</button>}
        </div>
      </section>

      {editing && (
        <section className="print-hidden border-b border-ink/10 px-6 py-5 sm:px-8">
          <StructuredEditor onCancel={() => setEditing(false)} onSaved={() => { setEditing(false); onEdited?.(); }} report={report} />
        </section>
      )}

      <div className="grid lg:grid-cols-[1.08fr_0.92fr]">
        <div className="border-b border-ink/10 p-5 lg:border-b-0 lg:border-r sm:p-7">
          <video className="aspect-video w-full rounded-2xl bg-black object-contain" controls onLoadedMetadata={(event) => { const length = event.currentTarget.duration; setPlayerDuration(Number.isFinite(length) && length > 0 ? length : null); }} ref={videoRef} src={run.playbackUrl} />
          <div className="mt-5 flex flex-wrap items-center gap-2 text-sm text-ink/65">
            <span className="text-xs font-bold uppercase tracking-[0.12em] text-ink/45">Incident window</span>
            {incident.startSeconds !== null ? (
              <button className="rounded-full border border-ink/10 px-3 py-1 font-mono text-xs font-bold text-moss hover:bg-moss/5" onClick={() => seek(incident.startSeconds!)} type="button">
                {formatClock(incident.startSeconds)}{incident.endSeconds !== null ? `–${formatClock(incident.endSeconds)}` : ''}
              </button>
            ) : <span>Not recorded</span>}
            {incident.duration !== null && <span className="text-xs text-ink/45">{incident.duration} s</span>}
            {windowEdited && original && original.startSeconds !== null && original.endSeconds !== null && (
              <span className="text-xs font-semibold text-clay" data-testid="window-edited">reviewer-set; model window {formatClock(original.startSeconds)}–{formatClock(original.endSeconds)}</span>
            )}
          </div>

          <ModelSection title="Model event timeline" source={modelOutput?.source}>
            {windowEdited && original && original.startSeconds !== null && original.endSeconds !== null && (
              <p className="mb-2 text-[11px] text-clay">Event times are the model&apos;s, relative to its original window {formatClock(original.startSeconds)}–{formatClock(original.endSeconds)}.</p>
            )}
            {modelOutput && modelOutput.timelineCheck && !modelOutput.timelineCheck.consistentWithWindow && (
              <p className="mb-2 rounded-xl border border-[#e8d49a] bg-[#fffaf0] p-3 text-xs leading-5 text-[#765300]" data-testid="timeline-inconsistent">
                Model-generated timeline, not consistent with the detected incident window
                {original && original.startSeconds !== null && original.endSeconds !== null ? ` (${formatClock(original.startSeconds)}–${formatClock(original.endSeconds)})` : ''}.
                {' '}Events outside the window are the model&apos;s context, not incident timestamps. The timeline is not scored and does not affect the report&apos;s validity.
              </p>
            )}
            {modelOutput?.timeline.length ? (
              <ol className="space-y-2">
                {modelOutput.timeline.map((event, index) => {
                  const clock = `${formatClock(event.startSeconds)}${event.endSeconds !== null && event.endSeconds !== event.startSeconds ? `–${formatClock(event.endSeconds)}` : ''}`;
                  const outsideWindow = event.insideWindow === false;
                  const seekable = event.seekable !== false && (playerDuration === null || timestampWithinVideo(event.startSeconds, playerDuration));
                  const tags = (
                    <>
                      {outsideWindow && <span className="rounded-full bg-ink/5 px-2 py-0.5 text-[10px] font-semibold uppercase tracking-wide text-ink/50" data-testid="event-outside-window">outside incident window</span>}
                      {!seekable && <span className="rounded-full bg-[#ffe8df] px-2 py-0.5 text-[10px] font-semibold uppercase tracking-wide text-[#9b3518]" data-testid="event-outside-video">outside the video</span>}
                    </>
                  );
                  return (
                    <li key={`${event.startSeconds}-${index}`}>
                      {seekable ? (
                        <button aria-label={`Play video from ${formatClock(event.startSeconds)}: ${event.description}`} className={`group flex w-full gap-4 rounded-xl border p-3 text-left transition hover:border-moss/30 hover:bg-moss/5 focus:outline-none focus:ring-2 focus:ring-signal ${outsideWindow ? 'border-dashed border-ink/15' : 'border-ink/8'}`} onClick={() => seek(event.startSeconds)} type="button">
                          <span className={`whitespace-nowrap font-mono text-xs font-bold ${outsideWindow ? 'text-ink/45' : 'text-moss'}`}>{clock}</span>
                          <span className={`text-sm leading-5 group-hover:text-ink ${outsideWindow ? 'text-ink/55' : 'text-ink/70'}`}>{event.description} {tags}</span>
                        </button>
                      ) : (
                        <div className="flex w-full gap-4 rounded-xl border border-dashed border-ink/15 p-3 text-left" data-testid="event-not-seekable">
                          <span className="whitespace-nowrap font-mono text-xs font-bold text-ink/40">{clock}</span>
                          <span className="text-sm leading-5 text-ink/50">{event.description} {tags}</span>
                        </div>
                      )}
                    </li>
                  );
                })}
              </ol>
            ) : <p className="rounded-xl border border-dashed border-ink/15 p-4 text-sm text-ink/45">{modelOutput ? 'The model returned no timestamped events.' : 'The original model output was not retained for this run.'}</p>}
          </ModelSection>
        </div>

        <div className="p-6 sm:p-8">
          <section>
            <h3 className="text-sm font-bold uppercase tracking-[0.12em] text-ink/45">Executive summary</h3>
            <p className="mt-3 whitespace-pre-wrap text-base leading-7 text-ink/75">{incident.description ?? 'No summary was recorded.'}</p>
          </section>

          <section className="mt-7 rounded-2xl bg-canvas p-5" data-testid="severity-panel">
            <h3 className="font-semibold">Severity {incident.severityLevel ?? '—'}/5</h3>
            {differences.severity && (
              <p className="mt-2 text-sm font-semibold text-clay" data-testid="severity-edited">
                Model assessed severity {differences.severity.model}/5; reviewer set {differences.severity.current}/5. The rationale below explains the model&apos;s assessment, not the reviewer&apos;s.
              </p>
            )}
            <p className="mt-3 text-xs font-bold uppercase tracking-[0.12em] text-ink/40">
              Model severity rationale{differences.severity ? ` (for model severity ${differences.severity.model}/5)` : ''}
            </p>
            <p className="mt-1 text-sm leading-6 text-ink/60">{modelOutput?.severityReason ?? 'No model rationale was retained for this run.'}</p>
          </section>

          <div className="mt-7 grid gap-5 sm:grid-cols-2">
            <EvidenceGroup
              title="Entities"
              empty="None identified"
              items={structured.entities.map((entity) => ({ id: entity.entityId, label: entity.type, text: entity.description }))}
            />
            <EvidenceGroup
              title="Instruments"
              empty="None identified"
              items={structured.instruments.map((instrument) => ({
                id: instrument.instrumentId,
                label: instrument.threatLevel !== null ? `threat ${instrument.threatLevel}/5` : 'threat unrated',
                text: `${instrument.name}: ${instrument.description}${instrument.entityId ? ` · held by ${holderLabel.get(instrument.entityId) ?? instrument.entityId}` : ''}`,
              }))}
            />
            <EvidenceGroup
              title="Assets"
              empty="None identified"
              items={structured.assets.map((asset) => ({ id: asset.assetId, text: `${asset.name}: ${asset.description}` }))}
            />
            {modelOutput && modelOutput.uncertainties.length > 0 && (
              <ModelSection compact title="Model-reported uncertainties" source={modelOutput.source}>
                <ul className="space-y-2 text-sm leading-5 text-ink/65">
                  {modelOutput.uncertainties.map((item, index) => <li className="border-l-2 border-clay/40 pl-3" key={`${item}-${index}`}>{item}</li>)}
                </ul>
              </ModelSection>
            )}
          </div>
        </div>
      </div>

      <RunDetailsPanel report={report} />

      <footer className="flex flex-col gap-3 border-t border-ink/10 bg-canvas/70 px-6 py-4 text-xs text-ink/45 sm:flex-row sm:items-center sm:justify-between">
        <span>{run.model} · {run.promptVersion || 'legacy prompt'} · {formatTimestamp(run.generatedAt, 'time unknown')}</span>
        <button className="font-semibold text-moss" onClick={onNewAnalysis} type="button">Analyze another video</button>
      </footer>
    </article>
  );
}

function ModelSection({ title, source, compact = false, children }: { title: string; source?: 'contract' | 'legacy'; compact?: boolean; children: ReactNode }) {
  return (
    <section className={compact ? '' : 'mt-6'}>
      <h3 className={`${compact ? 'text-xs' : 'text-sm'} font-bold uppercase tracking-[0.12em] text-ink/45`}>{title}</h3>
      <p className="mb-3 mt-1 text-[11px] text-ink/35">Original model output · read-only{source === 'legacy' ? ' · earlier prompt version' : ''}</p>
      {children}
    </section>
  );
}

function EvidenceGroup({ title, items, empty }: { title: string; items: Array<{ id: string; label?: string; text: string }>; empty: string }) {
  return (
    <section>
      <h3 className="text-xs font-bold uppercase tracking-[0.12em] text-ink/45">{title}</h3>
      {items.length ? (
        <ul className="mt-2 space-y-2 text-sm leading-5 text-ink/65">
          {items.map((item, index) => (
            <li className="border-l-2 border-signal/50 pl-3" key={`${item.id}-${index}`}>
              <span className="font-mono text-[11px] font-bold text-moss">{item.id}</span>
              {item.label && <span className="ml-2 rounded-full bg-canvas px-2 py-0.5 text-[11px] text-ink/55">{item.label}</span>}
              <span className="mt-0.5 block">{item.text}</span>
            </li>
          ))}
        </ul>
      ) : <p className="mt-2 text-sm italic text-ink/35">{empty}</p>}
    </section>
  );
}

function RunDetailsPanel({ report }: { report: ReportView }) {
  const { run } = report;
  const request = run.request;
  const response = run.response;
  return (
    <section className="border-t border-ink/10 px-6 py-6 sm:px-8">
      <details className="group rounded-2xl border border-ink/10 bg-canvas/60">
        <summary className="cursor-pointer list-none px-5 py-4 text-sm font-semibold focus:outline-none focus:ring-2 focus:ring-inset focus:ring-signal">
          <span className="flex items-center justify-between"><span>Run &amp; model output details</span><span className="text-ink/35 group-open:rotate-180">⌄</span></span>
        </summary>
        <div className="border-t border-ink/10 px-5 py-5">
          <dl className="grid gap-x-6 gap-y-4 text-xs sm:grid-cols-2 lg:grid-cols-4">
            <Provenance label="Model" value={run.model} />
            <Provenance label="Contract / prompt version" value={run.promptVersion || 'Legacy prompt'} />
            <Provenance label="Model run" value={run.modelRunId} />
            <Provenance label="Generated" value={formatTimestamp(run.generatedAt)} />
            {run.status && <Provenance label="Analysis outcome" value={`${OUTCOME_LABELS[run.status]}${run.statusInferred ? ' (recorded before outcomes were stored)' : ''}`} />}
            {request && <Provenance label="Additional instruction" value={request.additionalInstruction || 'None'} />}
            {response && <Provenance label="Finish reason" value={response.finishReason || 'Not returned'} />}
            {response && <Provenance label="Token usage" value={response.usage ? JSON.stringify(response.usage) : 'Not returned'} />}
            {request?.inferenceConfig && <Provenance label="Inference settings" value={JSON.stringify(request.inferenceConfig)} />}
            {request?.promptSha256 && <Provenance label="Prompt SHA-256" value={request.promptSha256} />}
            {request?.schemaSha256 && <Provenance label="Schema SHA-256" value={request.schemaSha256} />}
            {run.notesKind === 'contract' && <Provenance label="Validation policy" value={run.validation?.policy ?? 'Full contract validity (recorded before core-scored-v1)'} />}
            {run.validation?.fullContractValid !== undefined && <Provenance label="Full contract validity (first response)" value={run.validation.fullContractValid ? 'Valid' : 'Not valid: only unscored or ID issues, see below'} />}
            {request && 'videoDurationSeconds' in request && <Provenance label="Video length checked against" value={typeof request.videoDurationSeconds === 'number' ? `${Number(request.videoDurationSeconds.toFixed(3))} s` : 'Unknown (not checked)'} />}
          </dl>
          {(run.firstPassViolations ?? []).some((violation) => violation.scope === 'enrichment') && (
            <div className="mt-4 rounded-xl border border-ink/10 bg-white/60 p-4 text-xs text-ink/65" data-testid="enrichment-violations">
              <p className="font-semibold">Issues in unscored model fields (recorded, not repaired, do not affect validity)</p>
              <ul className="mt-1 list-disc pl-5">{(run.firstPassViolations ?? []).filter((violation) => violation.scope === 'enrichment').map((violation, index) => <li key={index}><span className="font-mono">{violation.code}</span>: {violation.message}</li>)}</ul>
            </div>
          )}
          {run.notesKind === 'invalid-contract' && <p className="mt-4 text-xs text-clay">The stored model output could not be re-validated: {run.notesError}</p>}
          {run.notesKind === 'none' && <p className="mt-4 text-xs italic text-ink/40">The original model output was not retained for this run.</p>}
          {run.status === 'valid_after_structural_repair' && <RepairDetails run={run} />}
          {run.rawModelOutput && <Block title={run.status === 'valid_after_structural_repair' ? 'Original raw model response (before ID normalization)' : 'Raw model response'}>{run.rawModelOutput}</Block>}
          {response?.reasoningContent && <Block title="Model reasoning">{response.reasoningContent}</Block>}
          {run.originalReport !== undefined && <Block title={run.status === 'valid_after_structural_repair' ? 'Validated model output (after ID normalization)' : 'Original validated model output'}>{JSON.stringify(run.originalReport, null, 2)}</Block>}
          {run.legacyReviewerEdits && <Block title="Reviewer edits made with the earlier editor">{JSON.stringify(run.legacyReviewerEdits, null, 2)}</Block>}
        </div>
      </details>
    </section>
  );
}

const OUTCOME_LABELS: Record<NonNullable<ReportView['run']['status']>, string> = {
  valid_first_pass: 'Valid on first pass',
  valid_after_structural_repair: 'Valid after structural repair',
  contract_failed: 'Contract failed',
  request_failed: 'Request failed',
};

function RepairDetails({ run }: { run: ReportView['run'] }) {
  const repair = run.repair ?? {};
  const operations = Array.isArray(repair.operations) ? (repair.operations as Array<Record<string, unknown>>) : [];
  const describe = (operation: Record<string, unknown>) => {
    if (operation.op === 'reorder') return `Reordered ${String(operation.collection)}: ${JSON.stringify(operation.from)} → ${JSON.stringify(operation.to)}`;
    if (operation.op === 'rename-id') return `Renamed ${String(operation.collection)} ID ${JSON.stringify(operation.from)} → ${JSON.stringify(operation.to)}`;
    if (operation.op === 'remap-reference') return `Updated reference ${String(operation.path)}: ${JSON.stringify(operation.from)} → ${JSON.stringify(operation.to)}`;
    return JSON.stringify(operation);
  };
  return (
    <div className="mt-6 rounded-xl border border-[#e8d49a] bg-[#fffaf0] p-4 text-xs text-ink/70" data-testid="repair-details">
      <h4 className="font-bold uppercase tracking-[0.12em] text-[#765300]">Contract repair applied (IDs only) · {String(repair.ruleSet ?? '')}</h4>
      <p className="mt-2">The model&apos;s first response broke only identifier rules. Identifiers and list order were normalized; no text or value was changed, and the result passed validation again.</p>
      <p className="mt-3 font-semibold">First-pass violations</p>
      <ul className="mt-1 list-disc pl-5">{(run.firstPassViolations ?? []).map((violation, index) => <li key={index}><span className="font-mono">{violation.code}</span>: {violation.message}</li>)}</ul>
      <p className="mt-3 font-semibold">Repair operations</p>
      <ul className="mt-1 list-disc pl-5">{operations.map((operation, index) => <li className="font-mono" key={index}>{describe(operation)}</li>)}</ul>
    </div>
  );
}

function Provenance({ label, value }: { label: string; value: string }) {
  return <div><dt className="font-bold uppercase tracking-[0.1em] text-ink/40">{label}</dt><dd className="mt-1 break-all font-mono text-ink/70">{value}</dd></div>;
}

function Block({ title, children }: { title: string; children: string }) {
  return (
    <div className="mt-6">
      <h4 className="text-xs font-bold uppercase tracking-[0.12em] text-ink/45">{title}</h4>
      <pre className="mt-2 max-h-80 overflow-auto whitespace-pre-wrap rounded-xl bg-ink p-4 font-mono text-xs leading-5 text-white/75">{children}</pre>
    </div>
  );
}
