// SPDX-License-Identifier: Apache-2.0
'use client';

import Link from 'next/link';
import { useEffect, useState } from 'react';
import type { AnalysisReport } from '@/lib/analysis/schema';
export function RunComparison({ videoId, left, right }: { videoId: string; left: string; right: string }) {
  const [reports, setReports] = useState<Array<AnalysisReport | null>>([null, null]); const [error, setError] = useState('');
  useEffect(() => { Promise.all([left, right].map((run) => fetch(`/api/reports/${encodeURIComponent(videoId)}?run=${encodeURIComponent(run)}`).then((r) => { if (!r.ok) throw new Error('Could not load a selected run'); return r.json() as Promise<{ report: AnalysisReport }>; }))).then((values) => setReports(values.map((value) => value.report))).catch((cause: Error) => setError(cause.message)); }, [videoId, left, right]);
  if (!left || !right) return <div className="mx-auto max-w-xl px-6 py-20 text-center"><h1 className="text-3xl font-semibold">Select two model runs from a report first.</h1></div>;
  return <div className="mx-auto max-w-[1500px] px-6 pb-20 pt-8 lg:px-12"><Link className="text-sm font-semibold text-moss" href={`/reports/${videoId}?run=${encodeURIComponent(left)}`}>← Back to report</Link><h1 className="mt-5 text-4xl font-semibold">Model-run comparison</h1>{error && <p className="mt-5 text-clay">{error}</p>}<div className="mt-8 grid gap-5 lg:grid-cols-2">{reports.map((report, index) => report ? <article className="rounded-3xl border border-ink/10 bg-white p-6" key={report.modelRunId}><p className="font-mono text-xs uppercase tracking-wider text-moss">{index === 0 ? 'Run A' : 'Run B'} · {new Date(report.generatedAt).toLocaleString()}</p><h2 className="mt-3 text-2xl font-semibold">{report.title}</h2><p className="mt-1 text-xs text-ink/45">{report.model} · {report.promptVersion || 'legacy prompt'}</p><dl className="mt-5 grid grid-cols-2 gap-3"><Field label="Type" value={report.incident_type} /><Field label="Severity" value={`${report.severity}/5`} /><Field label="Confidence" value={`${Math.round(report.confidence * 100)}%`} /><Field label="Time range" value={`${report.incident_start || '—'} – ${report.incident_end || '—'}`} /></dl><section className="mt-5"><h3 className="text-xs font-bold uppercase text-ink/40">Summary</h3><p className="mt-2 text-sm leading-6 text-ink/70">{report.description}</p></section><section className="mt-5"><h3 className="text-xs font-bold uppercase text-ink/40">Evidence</h3><ul className="mt-2 space-y-1 text-sm text-ink/65">{[...report.persons.map((x) => [x.description, x.actions].filter(Boolean).join(': ') || 'Person'), ...report.instruments.map((x) => `${x.name}: ${x.description}`), ...report.assets.map((x) => `${x.name}: ${x.description}`)].map((value, i) => <li key={i}>• {value}</li>)}</ul></section><section className="mt-5"><h3 className="text-xs font-bold uppercase text-ink/40">Timeline</h3><ol className="mt-2 space-y-2 text-sm text-ink/65">{report.timeline.map((event, i) => <li key={i}><strong>{Math.floor(event.start_seconds / 60)}:{String(Math.floor(event.start_seconds % 60)).padStart(2, '0')}</strong> {event.description}</li>)}</ol></section></article> : <div className="animate-pulse rounded-3xl bg-white p-10" key={index}>Loading run…</div>)}</div></div>;
}
function Field({ label, value }: { label: string; value: string }) { return <div className="rounded-xl bg-canvas p-3"><dt className="text-[10px] font-bold uppercase text-ink/40">{label}</dt><dd className="mt-1 text-sm font-semibold">{value}</dd></div>; }
